(function(){
  "use strict";
  const KEY="okinawa-slow-planner-v1",PHOTO_KEY="okinawa-slow-photos-v1",SAVED_KEY="okinawa-slow-saved-v1",CUSTOM_KEY="okinawa-slow-custom-v1";
  const areas=["全部","南部","那霸","中部","恩納・讀谷","北部"];
  const tags=["親子","雨天","海景","美食","購物","文化","自然","免門票"];
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));
  const clone=value=>JSON.parse(JSON.stringify(value));
  const uid=()=>`item-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
  const parseJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||"")||fallback}catch{return fallback}};
  const savedCustom=parseJSON(CUSTOM_KEY,[]),legacyCustom=parseJSON("threeSistersCustomDiscoveriesV1",[]).filter(x=>x&&x.name&&!savedCustom.some(y=>y.name===x.name)).map((x,index)=>({id:x.id||`legacy-custom-${index}`,name:x.name,kind:x.kind==="food"?"food":"spot",area:x.area||"那霸",category:x.type||"舊版自選",tags:["舊版自選"],desc:x.desc||"從舊版同步的自訂地點。",duration:90,time:x.time||"10:00",image:x.image||"",source:x.article||x.mapUrl||"https://www.google.com/maps",mapQuery:`${x.name} 沖繩`,tip:"從舊版自選清單同步。"}));
  const library=[...(window.OKINAWA_LIBRARY||[]),...legacyCustom,...savedCustom];
  const photoMap=window.OKINAWA_PHOTOS||{};
  library.forEach(place=>{const photo=photoMap[place.id];if(photo){place.image=photo.url;place.photoSource=photo.source;place.photoMatch=photo.match;place.photoTitle=photo.title}});
  const legacyFavoriteNames=parseJSON("okinawaFavorite",[]).map(x=>String(x).replace(/[🛍️⛩️👨‍👩‍👧‍👦🐠🌌🏛️🛝🌿🦆📍]/gu,"").trim());
  const legacyFavoriteIds=library.filter(p=>legacyFavoriteNames.some(name=>p.name.includes(name)||name.includes(p.name))).map(p=>p.id);
  let saved=new Set([...parseJSON(SAVED_KEY,[]),...legacyFavoriteIds]),photos=parseJSON(PHOTO_KEY,{}),activeDay=0,kindFilter="all",areaFilter="全部",tagFilter="",searchQuery="",visibleLimit=12,pendingPlace=null,pendingPhotoId=null,customIntent="library",toastTimer;
  const dismissedSuggestions={};

  const defaultTrip={title:"三姐妹旅遊去",style:"三姐妹慢遊",startDate:"2026-09-23",endDate:"2026-09-27",stays:["STORYLINE 瀨長島","JR九州 Hotel Blossom 那霸"],days:[
    {label:"抵達・瀨長島",note:"抵達日只留一個散步區，晚餐後就休息。",items:[
      item("13:30",90,"抵達那霸機場・領行李","交通","南部","must","預留入境、行李與取車時間。"),item("15:30",60,"STORYLINE 瀨長島入住","住宿","南部","must","先放行李、稍作休息。"),fromPlace("senagajima","17:00",90,"flex"),fromPlace("posillipo","18:30",100,"optional") ]},
    {label:"南部文化・親子",note:"今天只有一個大型主景點；下午保留飯店休息。",items:[fromPlace("okinawa-world","09:30",180,"must"),fromPlace("itoman-fisher","13:00",75,"flex"),item("15:00",120,"回飯店午休・泳池","休息","南部","must","親子行程真正留白，不另外塞點。"),fromPlace("iias","17:30",90,"optional")]},
    {label:"豐崎・移動那霸",note:"換飯店日避免跨區；下午只安排飯店周邊。",items:[item("09:30",60,"飯店早餐・退房","住宿","南部","must","慢慢整理行李。"),fromPlace("ashibinaa","10:45",105,"optional"),item("14:00",90,"JR九州 Hotel Blossom 那霸入住","住宿","那霸","must","寄放行李與休息。"),fromPlace("setsuko","15:45",60,"optional"),fromPlace("kokusai","17:00",100,"flex"),fromPlace("jack-steak","18:50",90,"optional")]},
    {label:"兒童王國・早休息",note:"兒童王國已足夠玩半天，下午回那霸休息。",items:[fromPlace("okinawa-zoo","10:00",240,"must"),fromPlace("aw","14:10",55,"optional"),item("15:30",120,"回那霸飯店午休","休息","那霸","must","避免孩子過累。"),fromPlace("ryukyu-no-ushi","18:00",120,"optional")]},
    {label:"最後採買・回程",note:"回程前至少預留 2.5 小時到機場。",items:[item("09:00",60,"飯店早餐・整理行李","住宿","那霸","must","退房前再次確認護照與行李。"),fromPlace("kokusai","10:30",60,"optional"),fromPlace("shuri-soba","11:40",60,"optional"),item("13:00",45,"前往那霸機場","交通","那霸","must","依實際班機調整，至少預留 2.5 小時。"),fromPlace("jimmy-airport","14:00",30,"optional")]}
  ]};
  function item(time,duration,title,category,area,priority,note){return{id:uid(),time,duration,title,kind:category==="住宿"||category==="交通"||category==="休息"?"note":"spot",category,area,priority,note,mapQuery:`${title} 沖繩`}}
  function fromPlace(id,time,duration,priority="flex"){const p=(window.OKINAWA_LIBRARY||[]).find(x=>x.id===id);return{id:uid(),placeId:id,time,duration:duration||p?.duration||90,title:p?.name||id,kind:p?.kind||"spot",category:p?.category||"景點",area:p?.area||"",priority,note:p?.tip||"",mapQuery:p?.mapQuery||`${p?.name||id} 沖繩`,image:p?.image||""}}
  let state=normalizeState(parseJSON(KEY,null)||clone(defaultTrip));
  if(state.title==="三姐妹出遊記")state.title="三姐妹旅遊去";
  if(state.style==="親子慢遊")state.style="三姐妹慢遊";
  save();

  function normalizeState(value){const next={...clone(defaultTrip),...value};next.stays=Array.isArray(next.stays)?next.stays:[];next.days=Array.isArray(next.days)&&next.days.length?next.days:clone(defaultTrip.days);next.days.forEach((day,index)=>{day.label=day.label||`Day ${index+1}`;day.note=day.note||"同一區慢慢玩，行程更舒服。";day.items=Array.isArray(day.items)?day.items:[];day.items.forEach(it=>{it.id=it.id||uid();it.duration=Number(it.duration)||90;it.priority=it.priority||"flex";it.area=it.area||"";it.category=it.category||it.kind||"景點"})});return next}
  function save(){localStorage.setItem(KEY,JSON.stringify(state))}
  function parseMinutes(time){if(!/^\d{2}:\d{2}$/.test(time||""))return 9999;const [h,m]=time.split(":").map(Number);return h*60+m}
  function timeFromMinutes(value){value=Math.max(0,Math.min(1439,value));return`${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`}
  function addDays(dateValue,offset){const d=new Date(`${dateValue}T12:00:00`);d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)}
  function formatDate(dateValue,weekday=true){const d=new Date(`${dateValue}T12:00:00`);return`${String(d.getMonth()+1).padStart(2,"0")}/${String(d.getDate()).padStart(2,"0")}${weekday?`（${"日一二三四五六"[d.getDay()]}）`:""}`}
  function dayDate(index){return addDays(state.startDate,index)}
  function dateCount(start,end){const a=new Date(`${start}T12:00:00`),b=new Date(`${end}T12:00:00`);return Math.max(1,Math.round((b-a)/86400000)+1)}
  function placeById(id){return library.find(p=>p.id===id)}
  function iconFor(it){if(it.kind==="food")return"餐";if(it.category==="交通")return"行";if(it.category==="住宿")return"宿";if(it.category==="休息")return"休";return"遊"}
  function priorityLabel(value){return value==="must"?"固定／重要":value==="optional"?"可跳過":"可彈性調整"}
  function mapURL(query){return`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`}
  function showToast(message){const el=$("toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2200)}

  function renderAll(){renderHero();renderDayTabs();renderTimeline();renderIdeas();renderFilters();renderLibrary();renderSettings();renderSources();applyHeroPhoto()}
  function renderHero(){const count=state.days.length;$("heroDates").textContent=`${formatDate(state.startDate,false)}－${formatDate(state.endDate,false)}`;$("heroPeople").textContent=state.style;$("heroCount").textContent=`${count} 天`;document.title=`${state.title}｜沖繩旅行計畫`}
  function renderDayTabs(){$("dayTabs").innerHTML=state.days.map((day,index)=>`<button class="day-tab ${index===activeDay?"active":""}" type="button" role="tab" aria-selected="${index===activeDay}" data-day="${index}"><span class="tab-count">${day.items.length}</span><b>Day ${index+1}</b><small>${formatDate(dayDate(index),false)}・${esc(day.label)}</small></button>`).join("")}
  function conflictsFor(items){const conflicts=new Set(),sorted=[...items].filter(x=>x.time).sort((a,b)=>parseMinutes(a.time)-parseMinutes(b.time));for(let i=0;i<sorted.length-1;i++){if(parseMinutes(sorted[i].time)+Number(sorted[i].duration)>parseMinutes(sorted[i+1].time)){conflicts.add(sorted[i].id);conflicts.add(sorted[i+1].id)}}return conflicts}
  function renderTimeline(){const day=state.days[activeDay],items=[...day.items].sort((a,b)=>parseMinutes(a.time)-parseMinutes(b.time)),conflicts=conflictsFor(items),total=items.reduce((sum,it)=>sum+Number(it.duration||0),0),level=total<=360?1:total<=540?2:total<=720?3:4;$("activeDayDate").textContent=formatDate(dayDate(activeDay));$("activeDayTitle").textContent=day.label;$("dayNote").textContent=`當日備註｜${day.note}`;$("loadMeter").innerHTML=`<b>行程量${level===1?"低":level===2?"適中":level===3?"偏高":"過高"}</b><small>共 ${Math.round(total/60*10)/10} 小時</small><span class="load-dots">${[1,2,3,4].map(x=>`<i class="${x<=level?"on":""}"></i>`).join("")}</span>`;$("timeline").innerHTML=items.length?items.map(it=>{const end=parseMinutes(it.time)+Number(it.duration),conflict=conflicts.has(it.id);return`<article class="timeline-item ${esc(it.priority)} ${conflict?"conflict":""}" data-item-id="${esc(it.id)}"><div class="time-block"><input type="time" value="${esc(it.time)}" data-time-id="${esc(it.id)}" aria-label="${esc(it.title)}開始時間"><small>${timeFromMinutes(end)}</small></div><span class="timeline-dot"></span><div class="timeline-body"><h4><span aria-hidden="true">${iconFor(it)}・</span>${esc(it.title)}</h4><div class="timeline-meta"><span class="priority-pill">${priorityLabel(it.priority)}</span><span>${esc(it.area||"彈性地點")}</span><span>${Number(it.duration)} 分鐘</span></div>${it.note?`<p class="timeline-note">${esc(it.note)}</p>`:""}${conflict?`<span class="conflict-label">時間重疊，請調整開始時間</span>`:""}<div class="timeline-tools"><button type="button" data-move="up" data-id="${esc(it.id)}" aria-label="往前 30 分鐘">↑</button><button type="button" data-move="down" data-id="${esc(it.id)}" aria-label="往後 30 分鐘">↓</button><button type="button" data-remove="${esc(it.id)}" aria-label="刪除">×</button></div></div></article>`}).join(""):`<div class="timeline-empty"><b>尚未安排行程</b>從景點與美食加入項目。</div>`}
  function renderIdeas(){
    const day=state.days[activeDay],items=day.items,conflicts=conflictsFor(items),areasUsed=items.filter(x=>x.area).map(x=>x.area),areaCounts=areasUsed.reduce((acc,a)=>(acc[a]=(acc[a]||0)+1,acc),{}),mainArea=Object.entries(areaCounts).sort((a,b)=>b[1]-a[1])[0]?.[0]||suggestArea(activeDay),foods=items.filter(x=>x.kind==="food"),hasLunch=foods.some(x=>{const m=parseMinutes(x.time);return m>=660&&m<=840}),hasDinner=foods.some(x=>{const m=parseMinutes(x.time);return m>=1020&&m<=1260}),total=items.reduce((s,x)=>s+Number(x.duration||0),0),advice=[];
    if(conflicts.size)advice.push(["時間重疊",`有 ${conflicts.size} 個項目重疊，請先調整開始時間。`]);else if(new Set(areasUsed).size>=3)advice.push(["跨區過多",`目前包含 ${new Set(areasUsed).size} 個地區，建議以 ${mainArea} 為主要區域。`]);else advice.push(["區域安排",mainArea?`當日以 ${mainArea} 為主，新增項目時優先選擇同區。`:"請先加入一個主要景點，再選擇同區餐飲。"]);
    if(!hasLunch)advice.push(["缺少午餐",`建議加入 ${mainArea} 11:30～13:30 的餐飲。`]);else if(!hasDinner)advice.push(["缺少晚餐","若選擇熱門餐廳，請先加入行程並確認預約。"]);
    if(total>660)advice.push(["行程量過高","建議將購物、甜點或散步設為可跳過。"]);else if(total<360)advice.push(["可新增備案","可加入咖啡、短停景點或雨天備案。"]);
    $("smartAdvice").innerHTML=advice.slice(0,3).map(a=>`<div class="advice-card"><b>${esc(a[0])}</b>${esc(a[1])}</div>`).join("");
    const used=new Set(items.map(x=>x.placeId)),dismissed=dismissedSuggestions[activeDay]||new Set(),eligible=p=>!used.has(p.id)&&!dismissed.has(p.id),sort=(list,needFood=false)=>list.sort((a,b)=>scoreSuggestion(b,day,mainArea,needFood)-scoreSuggestion(a,day,mainArea,needFood));
    const layers=[
      {label:"主行程",hint:"同區景點",list:sort(library.filter(p=>eligible(p)&&p.area===mainArea&&p.kind==="spot"))},
      {label:"同區餐飲",hint:!hasLunch?"午餐選項":"餐飲選項",list:sort(library.filter(p=>eligible(p)&&p.area===mainArea&&p.kind==="food"),true)},
      {label:"親子備案",hint:"親子選項",list:sort(library.filter(p=>eligible(p)&&p.tags.includes("親子")&&(p.area===mainArea||p.duration<=120)))},
      {label:"雨天備案",hint:"雨天選項",list:sort(library.filter(p=>eligible(p)&&p.tags.includes("雨天")&&(p.area===mainArea||p.duration<=150)))}
    ];
    const chosen=[],chosenIds=new Set();layers.forEach(layer=>{const place=layer.list.find(p=>!chosenIds.has(p.id));if(place){chosenIds.add(place.id);chosen.push({...layer,place})}});
    $("smartSuggestions").innerHTML=`<div class="idea-title-row"><p>推薦項目（按 × 更換）</p>${dismissed.size?`<button type="button" data-action="reset-suggestions">重設</button>`:""}</div>${chosen.map(({label,hint,place})=>`<div class="idea-place"><span class="idea-layer" data-layer="${esc(label)}">${esc(label)}</span><span class="idea-copy"><b>${esc(place.name)}</b><small>${esc(hint)}・${esc(place.area)}・${esc(place.category)}</small></span><button class="idea-add" type="button" data-add-place="${esc(place.id)}" aria-label="加入${esc(place.name)}">＋</button><button class="idea-dismiss" type="button" data-dismiss-suggestion="${esc(place.id)}" aria-label="更換${esc(place.name)}">×</button></div>`).join("")||`<div class="advice-card">沒有更多推薦項目。按「重設」重新顯示。</div>`}`;
  }
  function suggestArea(index){return["南部","南部","那霸","中部","那霸"][index]||"那霸"}
  function scoreSuggestion(p,day,area,needFood){let score=p.area===area?5:0;if(needFood&&p.kind==="food")score+=6;if(state.style.includes("親子")&&p.tags.includes("親子"))score+=3;if(saved.has(p.id))score+=2;if(p.tags.includes("雨天"))score+=1;return score}

  function renderFilters(){if(!$("areaFilters").children.length)$("areaFilters").innerHTML=areas.map(a=>`<button type="button" class="${a===areaFilter?"active":""}" data-area="${esc(a)}">${esc(a)}</button>`).join("");else [...$("areaFilters").children].forEach(b=>b.classList.toggle("active",b.dataset.area===areaFilter));if(!$("tagFilters").children.length)$("tagFilters").innerHTML=tags.map(t=>`<button type="button" data-tag="${esc(t)}">${esc(t)}</button>`).join("");[...$("tagFilters").children].forEach(b=>b.classList.toggle("active",b.dataset.tag===tagFilter));[...$("kindFilter").querySelectorAll("button")].forEach(b=>b.classList.toggle("active",b.dataset.kind===kindFilter))}
  function filteredLibrary(){const q=searchQuery.trim().toLowerCase();return library.filter(p=>(kindFilter==="all"||(kindFilter==="saved"?saved.has(p.id):p.kind===kindFilter))&&(areaFilter==="全部"||p.area===areaFilter)&&(!tagFilter||p.tags.includes(tagFilter))&&(!q||`${p.name} ${p.area} ${p.category} ${p.tags.join(" ")} ${p.desc}`.toLowerCase().includes(q)))}
  function readableDuration(minutes){return minutes>=60&&minutes%60===0?`${minutes/60} 小時`:minutes>60?`${Math.floor(minutes/60)} 小時 ${minutes%60} 分`:`${minutes} 分鐘`}
  function recommendReason(p){if(p.tip)return p.tip;if(p.tags.includes("雨天"))return"天氣不穩時可優先保留，室內或遮蔽較完整。";if(p.kind==="food")return`適合放在 ${p.time||"用餐時段"}，優先搭配 ${p.area} 當日路線。`;return`安排在 ${p.area} 行程日，能減少跨區移動。`}
  function renderLibrary(){const results=filteredLibrary(),visible=results.slice(0,visibleLimit);$("resultSummary").textContent=`${results.length} 筆結果${areaFilter!=="全部"?`・${areaFilter}`:""}${tagFilter?`・${tagFilter}`:""}`;$("libraryGrid").innerHTML=visible.map(p=>`<article class="place-card"><div class="place-cover" style="background-image:url('${esc(photos[p.id]||p.image)}')"><span class="place-kind">${p.kind==="food"?"美食":"景點"}・${esc(p.category)}</span><button class="save-button ${saved.has(p.id)?"saved":""}" type="button" data-save="${esc(p.id)}" aria-label="收藏${esc(p.name)}">${saved.has(p.id)?"♥":"♡"}</button><button class="photo-edit" type="button" data-photo-id="${esc(p.id)}">換照片</button>${p.photoSource&&!photos[p.id]?`<a class="photo-source" href="${esc(p.photoSource)}" target="_blank" rel="noopener">${p.photoMatch==="direct"?"實景照片":"實拍示意"} ↗</a>`:""}</div><div class="place-body"><div class="place-top"><h3>${esc(p.name)}</h3><span class="area-label">${esc(p.area)}</span></div><p>${esc(p.desc)}</p><div class="place-reason"><b>安排建議</b><span>${esc(recommendReason(p))}</span></div><div class="place-facts"><span>停留 ${esc(readableDuration(Number(p.duration)||90))}</span><span>建議時間 ${esc(p.time||"彈性")}</span></div><div class="place-tags">${p.tags.slice(0,3).map(t=>`<span>${esc(t)}</span>`).join("")}</div><div class="place-actions"><button class="add-place" type="button" data-add-place="${esc(p.id)}">＋ 加入行程</button><a class="map-link" href="${mapURL(p.mapQuery)}" target="_blank" rel="noopener" aria-label="在地圖查看${esc(p.name)}">地圖</a><a class="source-link" href="${esc(p.source)}" target="_blank" rel="noopener" aria-label="查看${esc(p.name)}來源">來源</a></div></div></article>`).join("");$("showMore").hidden=visible.length>=results.length}
  function renderSettings(){$("tripTitle").value=state.title;$("tripStyle").value=state.style;$("startDate").value=state.startDate;$("endDate").value=state.endDate;$("staysInput").value=state.stays.join("、")}
  function renderSources(){if($("sourceLinks").children.length)return;$("sourceLinks").innerHTML=(window.OKINAWA_SOURCES||[]).map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.label)} ↗</a>`).join("")}
  function applyHeroPhoto(){$("heroPhoto").style.backgroundImage=`url("${String(photos.hero||"./assets/okinawa-beach-animals-v2.webp").replace(/"/g,"%22")}")`}

  function closeDialog(dialog){if(dialog?.open)dialog.close()}
  function openQuickSearch(term=""){const dialog=$("quickSearchDialog"),input=$("quickSearchInput");if(!dialog.open)dialog.showModal();input.value=term;renderQuickResults(term);setTimeout(()=>input.focus(),30)}
  function quickSearchData(query){const q=query.trim().toLowerCase(),planner=[];state.days.forEach((day,dayIndex)=>day.items.forEach(it=>planner.push({type:"planner",dayIndex,title:it.title,meta:`Day ${dayIndex+1}・${it.time}・${it.area||day.label}`,search:`${it.title} ${it.area} ${it.category} ${it.note}`})));const places=library.map(p=>({type:"place",placeId:p.id,title:p.name,meta:`${p.kind==="food"?"美食":"景點"}・${p.area}・${p.category}`,search:`${p.name} ${p.area} ${p.category} ${p.tags.join(" ")} ${p.desc}`}));if(!q)return[...planner.slice(0,4),...places.filter(x=>saved.has(x.placeId)).slice(0,4),...places.filter(x=>["senagajima","okinawa-world","churaumi","kokusai"].includes(x.placeId)).slice(0,4)].slice(0,10);return[...planner,...places].filter(x=>`${x.title} ${x.meta} ${x.search}`.toLowerCase().includes(q)).slice(0,20)}
  function renderQuickResults(query){const results=quickSearchData(query);$("quickSearchResults").innerHTML=results.length?results.map(x=>`<button class="quick-result" type="button" ${x.type==="place"?`data-quick-place="${esc(x.placeId)}"`:`data-quick-day="${x.dayIndex}"`}><span class="quick-result-icon">${x.type==="place"?(placeById(x.placeId)?.kind==="food"?"餐":"遊"):"排"}</span><span><b>${esc(x.title)}</b><small>${esc(x.meta)}</small></span><em>${x.type==="place"?"加入 ＋":"查看 →"}</em></button>`).join(""):`<div class="quick-empty">找不到符合的項目，試試地區、料理或「雨天」。</div>`}
  function openQuickPlace(id){const place=placeById(id);closeDialog($("quickSearchDialog"));if(place)openSchedule(place)}
  function jumpQuickDay(index){closeDialog($("quickSearchDialog"));activeDay=Number(index);renderDayTabs();renderTimeline();renderIdeas();$("planner").scrollIntoView({behavior:"smooth",block:"start"})}

  function openSchedule(place){pendingPlace=place;$("scheduleTitle").textContent=`加入「${place.name}」`;$("scheduleDay").innerHTML=state.days.map((d,i)=>`<option value="${i}" ${i===activeDay?"selected":""}>Day ${i+1}・${esc(d.label)}</option>`).join("");$("scheduleTime").value=recommendedTime(place);$("scheduleDuration").value=String(place.duration||90);$("schedulePriority").value="flex";$("scheduleNote").value=place.tip||"";$("scheduleDialog").showModal()}
  function recommendedTime(place){const day=state.days[activeDay],base=parseMinutes(place.time||"10:00"),last=Math.max(...day.items.map(x=>parseMinutes(x.time)+Number(x.duration||0)),0);if(place.kind==="food"){if(base<900&&!day.items.some(x=>x.kind==="food"&&parseMinutes(x.time)<900))return place.time||"12:00";if(last>960)return timeFromMinutes(Math.max(1080,last+20))}return timeFromMinutes(Math.max(base,last&&last<1200?last+20:base))}
  function addScheduled(){if(!pendingPlace)return;const dayIndex=Number($("scheduleDay").value);state.days[dayIndex].items.push({id:uid(),placeId:pendingPlace.id,time:$("scheduleTime").value,duration:Number($("scheduleDuration").value),title:pendingPlace.name,kind:pendingPlace.kind,category:pendingPlace.category,area:pendingPlace.area,priority:$("schedulePriority").value,note:$("scheduleNote").value.trim(),mapQuery:pendingPlace.mapQuery,image:photos[pendingPlace.id]||pendingPlace.image});activeDay=dayIndex;save();$("scheduleDialog").close();renderDayTabs();renderTimeline();renderIdeas();showToast(`已加入 Day ${dayIndex+1}`);$("planner").scrollIntoView({behavior:"smooth",block:"start"})}
  function openCustom(intent){customIntent=intent;$("customForm").reset();$("customDialog").showModal();setTimeout(()=>$("customName").focus(),80)}
  function addCustomPlace(){const place={id:`custom-${Date.now()}`,name:$("customName").value.trim(),kind:$("customKind").value,area:$("customArea").value,category:$("customCategory").value.trim()||($("customKind").value==="food"?"自選美食":"自選景點"),tags:["自訂"],desc:$("customDescription").value.trim()||"自訂沖繩地點。",duration:90,time:$("customKind").value==="food"?"12:00":"10:00",image:$("customKind").value==="food"?"https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=900&q=82":"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=82",source:"https://www.google.com/maps",mapQuery:`${$("customName").value.trim()} 沖繩`,tip:""};if(!place.name)return;library.unshift(place);localStorage.setItem(CUSTOM_KEY,JSON.stringify(library.filter(p=>p.id.startsWith("custom-"))));$("customDialog").close();areaFilter="全部";kindFilter=place.kind;visibleLimit=12;renderFilters();renderLibrary();showToast("已新增地點");if(customIntent==="schedule")openSchedule(place)}

  function openPhoto(id){pendingPhotoId=id;$("photoUrl").value=photos[id]&&!photos[id].startsWith("data:")?photos[id]:"";$("photoFile").value="";$("photoDialog").showModal()}
  async function applyPhoto(){const file=$("photoFile").files[0],url=$("photoUrl").value.trim();if(file)photos[pendingPhotoId]=await resizeImage(file);else if(url)photos[pendingPhotoId]=url;else return showToast("請貼上網址或選擇照片");localStorage.setItem(PHOTO_KEY,JSON.stringify(photos));$("photoDialog").close();pendingPhotoId==="hero"?applyHeroPhoto():renderLibrary();showToast("照片已更換")}
  function resizeImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const image=new Image();image.onerror=reject;image.onload=()=>{const max=1100,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement("canvas");canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/webp",.8))};image.src=reader.result};reader.readAsDataURL(file)})}
  function resetPhoto(){delete photos[pendingPhotoId];localStorage.setItem(PHOTO_KEY,JSON.stringify(photos));$("photoDialog").close();pendingPhotoId==="hero"?applyHeroPhoto():renderLibrary();showToast("已恢復預設照片")}

  function universalJSON(){return{schemaVersion:1,id:`okinawa-${state.startDate}`,title:state.title,shortTitle:"沖繩旅行手札",destination:"日本・沖繩",subtitle:`${state.days.length} 天 ${state.style}自由行`,startDate:state.startDate,endDate:state.endDate,timeZone:"Asia/Tokyo",locale:"zh-TW",heroImage:photos.hero||"./assets/okinawa-beach-animals-v2.webp",theme:{primary:"#438f8f",primaryDark:"#596f91",accent:"#e98273",background:"#faf3e8",card:"#fffdfa"},badges:[`🌺 ${state.style}`,"🗓️ 清楚時間軸","✨ 保留彈性"],alerts:["熱門餐廳、主題樂園與海上活動請事先確認預約。","營業時間、休館日與交通可能變動，出發前請再查官方資訊。","海鮮過敏者請主動詢問共鍋、共用器具與交叉接觸。"],delayRules:[{title:"先刪可跳過項目",text:"購物、甜點與散步可縮短；固定預約、交通與飯店不動。"},{title:"一天一個主景點",text:"大型園區或長車程日不要再塞第二個大點。"},{title:"同區吃與玩",text:"午餐、晚餐優先選當日主要地區，減少來回車程。"}],stays:state.stays.map((name,index)=>({icon:"🏨",name,dates:index===0?"前段住宿":"後段住宿",note:"依實際訂房日期調整。",mapQuery:`${name} 沖繩`})),days:state.days.map((day,dayIndex)=>({id:`day-${dayIndex+1}`,date:dayDate(dayIndex),label:day.label,icon:dayIndex===0?"🛬":dayIndex===state.days.length-1?"🛫":"🌺",items:[...day.items].sort((a,b)=>parseMinutes(a.time)-parseMinutes(b.time)).map((it,index)=>{const end=timeFromMinutes(parseMinutes(it.time)+Number(it.duration||90));return{id:`${it.placeId||"custom"}-${index+1}`,time:it.time,end,title:it.title,icon:it.kind==="food"?"🍴":it.category==="交通"?"🚗":it.category==="住宿"?"🏨":it.category==="休息"?"☕":"📍",priority:it.priority,place:it.title,description:[it.note,it.area?`地區：${it.area}`:""].filter(Boolean).join("｜"),mapQuery:it.mapQuery||`${it.title} 沖繩`,image:it.placeId?(photos[it.placeId]||it.image||""):""}})})),activityDecisionGuide:{days:state.days.map((day,index)=>({dayId:`day-${index+1}`,decisions:day.items.map((it,itemIndex)=>({itemId:`${it.placeId||"custom"}-${itemIndex+1}`,decision:it.priority==="must"?"參加":it.priority==="optional"?"看體力":"彈性",fatigue:Number(it.duration)>180?"高":Number(it.duration)>90?"中":"低",reason:it.priority==="optional"?"時間不足時可先刪。":"依同區動線安排。"}))}))}}}
  function exportJSON(){const data=universalJSON();data.shortTitle="三姐妹旅遊去";const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`three-sisters-okinawa-${state.startDate}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast("已匯出三姐妹旅遊去 JSON")}
  async function importJSON(file){try{const data=JSON.parse(await file.text());if(!data||![1,2].includes(data.schemaVersion)||!Array.isArray(data.days))throw new Error("格式不符");state={title:data.title||"沖繩旅行",style:(data.badges?.[0]||"自由行").replace(/^\S+\s*/,""),startDate:data.startDate||data.days[0]?.date,endDate:data.endDate||data.days.at(-1)?.date,stays:(data.stays||[]).map(x=>x.name),days:data.days.map(day=>({label:day.label||"行程",note:"從通用 JSON 匯入，可繼續調整。",items:(day.items||[]).map(it=>({id:uid(),time:it.time||"10:00",duration:Math.max(30,(parseMinutes(it.end)-parseMinutes(it.time))||90),title:it.title,kind:/🍴|餐|食/.test(`${it.icon}${it.title}`)?"food":"spot",category:"匯入行程",area:(it.description||"").match(/地區：([^｜]+)/)?.[1]||"",priority:it.priority||"flex",note:it.description||"",mapQuery:it.mapQuery||it.place||it.title,image:it.image||""}))}))};state=normalizeState(state);activeDay=0;save();renderAll();showToast("行程 JSON 已讀取")}catch(error){showToast("無法讀取：請確認是通用行程 JSON")}}
  function applyTemplate(){if(!confirm("套用親子範本會取代目前的每日行程，確定嗎？"))return;const details={title:state.title,style:state.style,startDate:state.startDate,endDate:state.endDate,stays:state.stays};state=normalizeState({...clone(defaultTrip),...details});activeDay=0;save();renderAll();showToast("已套用親子範本")}
  function updateTrip(event){event.preventDefault();const start=$("startDate").value,end=$("endDate").value;if(!start||!end||end<start)return showToast("回程日期不能早於出發日期");const count=dateCount(start,end);state.title=$("tripTitle").value.trim()||"沖繩旅行";state.style=$("tripStyle").value;state.startDate=start;state.endDate=end;state.stays=$("staysInput").value.split(/[、,，]/).map(x=>x.trim()).filter(Boolean);while(state.days.length<count)state.days.push({label:"自由安排",note:"先選一個主景點，再找同區美食。",items:[]});state.days=state.days.slice(0,count);activeDay=Math.min(activeDay,count-1);save();renderAll();showToast("旅程設定已更新")}

  document.addEventListener("click",event=>{
    const button=event.target.closest("button");if(!button)return;const action=button.dataset.action;
    if(button.hasAttribute("data-close-dialog")){closeDialog(button.closest("dialog"));return}
    if(button.dataset.quickTerm!==undefined){$("quickSearchInput").value=button.dataset.quickTerm;renderQuickResults(button.dataset.quickTerm);$("quickSearchInput").focus();return}
    if(button.dataset.quickPlace)return openQuickPlace(button.dataset.quickPlace);
    if(button.dataset.quickDay!==undefined)return jumpQuickDay(button.dataset.quickDay);
    if(button.dataset.dismissSuggestion){dismissedSuggestions[activeDay]??=new Set();dismissedSuggestions[activeDay].add(button.dataset.dismissSuggestion);renderIdeas();return}
    if(button.dataset.day!==undefined){activeDay=Number(button.dataset.day);renderDayTabs();renderTimeline();renderIdeas();return}
    if(button.dataset.addPlace)return openSchedule(placeById(button.dataset.addPlace));
    if(button.dataset.save){saved.has(button.dataset.save)?saved.delete(button.dataset.save):saved.add(button.dataset.save);localStorage.setItem(SAVED_KEY,JSON.stringify([...saved]));renderLibrary();return}
    if(button.dataset.photoId)return openPhoto(button.dataset.photoId);
    if(button.dataset.area!==undefined){areaFilter=button.dataset.area;visibleLimit=12;renderFilters();renderLibrary();return}
    if(button.dataset.tag!==undefined){tagFilter=tagFilter===button.dataset.tag?"":button.dataset.tag;visibleLimit=12;renderFilters();renderLibrary();return}
    if(button.dataset.kind){kindFilter=button.dataset.kind;visibleLimit=12;renderFilters();renderLibrary();return}
    if(button.dataset.remove){const day=state.days[activeDay];day.items=day.items.filter(x=>x.id!==button.dataset.remove);save();renderDayTabs();renderTimeline();renderIdeas();showToast("已從時間軸移除");return}
    if(button.dataset.move){const it=state.days[activeDay].items.find(x=>x.id===button.dataset.id);if(it){it.time=timeFromMinutes(parseMinutes(it.time)+(button.dataset.move==="up"?-30:30));save();renderTimeline();renderIdeas()}return}
    if(action==="quick-search")openQuickSearch();
    if(action==="reset-suggestions"){dismissedSuggestions[activeDay]=new Set();renderIdeas()}
    if(action==="export")exportJSON();if(action==="import")$("importFile").click();if(action==="template")applyTemplate();if(action==="add-custom")openCustom("schedule");if(action==="add-library")openCustom("library");if(action==="scroll-explore")$("explore").scrollIntoView({behavior:"smooth"});if(action==="reset-photo")resetPhoto()
  });
  document.addEventListener("change",event=>{if(event.target.matches("[data-time-id]")){const it=state.days[activeDay].items.find(x=>x.id===event.target.dataset.timeId);if(it){it.time=event.target.value;save();renderTimeline();renderIdeas()}}});
  $("librarySearch").addEventListener("input",event=>{searchQuery=event.target.value;visibleLimit=12;renderLibrary()});$("quickSearchInput").addEventListener("input",event=>renderQuickResults(event.target.value));$("showMore").addEventListener("click",()=>{visibleLimit+=12;renderLibrary()});$("scheduleForm").addEventListener("submit",event=>{event.preventDefault();addScheduled()});$("customForm").addEventListener("submit",event=>{event.preventDefault();addCustomPlace()});$("photoForm").addEventListener("submit",async event=>{event.preventDefault();await applyPhoto()});$("tripForm").addEventListener("submit",updateTrip);$("importFile").addEventListener("change",event=>{const file=event.target.files[0];if(file)importJSON(file);event.target.value=""});
  document.addEventListener("keydown",event=>{const shortcut=(event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k",slash=event.key==="/"&&!/input|textarea|select/i.test(document.activeElement?.tagName||"");if(shortcut||slash){event.preventDefault();openQuickSearch()}});
  document.querySelectorAll("dialog").forEach(dialog=>dialog.addEventListener("click",event=>{if(event.target===dialog)closeDialog(dialog)}));
  if("serviceWorker" in navigator&&location.protocol.startsWith("http"))window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"));
  renderAll();
})();
