(function(){
  const img={sea:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=82",aquarium:"https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=900&q=82",forest:"https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=900&q=82",city:"https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=900&q=82",culture:"https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=900&q=82",park:"https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=82",shop:"https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=900&q=82",soba:"https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=82",meat:"https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=900&q=82",seafood:"https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=900&q=82",cafe:"https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=82",burger:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=82",sweet:"https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=900&q=82"};
  const official="https://visitokinawajapan.com/zh-hant/destinations/okinawa-main-island/";
  const mimi="https://mimihan.tw/okinawa-family-trip/";
  const foodBlog="https://mimihan.tw/okinawa-foods/";
  const aiko="https://aikolife.com/okinawa/";
  const youtube="https://www.youtube.com/watch?v=pEvaKcmK1Lo";
  const umikaji="https://www.umikajiterrace.com/shop-restaurants/";
  const familyIndoor="https://ayaca.tw/okinawa-rainy-day-indoor-family/";
  const familyJapan="https://www.asoview.com/note/5490/";
  const add=(id,name,kind,area,category,tags,desc,duration,time,image,source=official,tip="")=>({id,name,kind,area,category,tags,desc,duration,time,image,source,tip,mapQuery:`${name} 沖繩`});
  window.OKINAWA_LIBRARY=[
    add("senagajima","瀨長島 Umikaji Terrace","spot","南部","海景散步",["海景","夕陽","親子","免門票"],"離機場近，適合抵達日看夕陽、吃晚餐，不必再拉長車程。",120,"16:30",img.sea,aiko,"傍晚最舒服；和豐崎排同一天很順。"),
    add("okinawa-world","沖繩世界・玉泉洞","spot","南部","文化・洞窟",["經典","親子","雨天","室內"],"鐘乳石洞、琉球文化與表演集中，第一次來沖繩很完整。",180,"09:30",img.culture,mimi,"至少留 3 小時，別再塞另一個大型景點。"),
    add("dmm","DMM Kariyushi 水族館","spot","南部","水族館",["親子","雨天","室內","療癒"],"在 iias 豐崎旁，適合雨天或回程前半日，移動負擔小。",120,"10:00",img.aquarium,aiko,"可直接接 iias 吃飯與採買。"),
    add("itoman-market","糸滿魚市場・鮮魚中心","spot","南部","市場",["美食","雨天","在地","親子"],"海鮮、熟食與小吃可各自挑選，適合午餐前後短停。",75,"11:00",img.seafood,foodBlog,"對海鮮過敏者要留意共用器具與交叉接觸。"),
    add("oujima","奧武島","spot","南部","離島散步",["海景","小吃","慢遊","免門票"],"開車過橋即可到的小島，適合海邊散步與現炸天婦羅。",90,"14:30",img.sea,aiko),
    add("chinen","知念岬公園","spot","南部","海景公園",["海景","免門票","長輩","短停"],"開闊海景、步行負擔低，可和齋場御嶽或南城咖啡搭配。",45,"15:00",img.sea,official),
    add("sefa-utaki","齋場御嶽","spot","南部","世界遺產",["文化","自然","安靜","步行"],"琉球王國重要聖地，適合喜歡歷史與森林氣氛的旅人。",90,"09:30",img.forest,official,"石板路與坡度較多，雨天鞋底要防滑。"),
    add("peace-park","沖繩平和祈念公園","spot","南部","歷史公園",["歷史","戶外","長輩","免門票"],"海景與戰爭歷史並存，園區大，建議選重點參觀。",100,"10:00",img.park,official),
    add("iias","iias 沖繩豐崎","spot","南部","購物商場",["購物","親子","雨天","室內"],"水族館、餐廳、超市與店舖集中，適合安排成彈性備案。",120,"16:00",img.shop,aiko),
    add("ashibinaa","沖繩 Outlet Mall Ashibinaa","spot","南部","購物商場",["購物","雨天","品牌","彈性"],"距離機場與豐崎近，適合只逛重點品牌，不必排滿半天。",120,"10:30",img.shop,aiko),
    add("kokusai","國際通","spot","那霸","街區散步",["購物","美食","夜間","免門票"],"那霸最方便的逛街吃飯區，住市區可拆成多個晚上慢慢逛。",120,"17:00",img.city,official,"不要把所有採買塞在最後一天。"),
    add("makishi","第一牧志公設市場","spot","那霸","市場",["美食","在地","雨天","文化"],"被稱作那霸廚房，一樓選食材、二樓用餐，周邊巷弄也好逛。",90,"11:00",img.seafood,official),
    add("shuri","首里城公園","spot","那霸","世界遺產",["經典","文化","歷史","戶外"],"理解琉球王國的代表景點，建議連同守禮門與周邊散步。",120,"09:30",img.culture,official,"正殿重建狀況與開放區域請出發前確認。"),
    add("kinjo-road","首里金城町石疊道","spot","那霸","歷史散步",["文化","安靜","拍照","免費"],"約 300 公尺的老石板路，適合與首里城合併，不需另跑一趟。",50,"11:30",img.culture,official,"坡陡且滑，推車與長輩可略過。"),
    add("naminoue","波上宮・波之上海灘","spot","那霸","神社・海灘",["神社","海景","短停","免門票"],"市區就能參拜與看海，適合安排在早晨或回飯店前。",60,"16:30",img.sea,official),
    add("museum","沖繩縣立博物館・美術館","spot","那霸","博物館",["雨天","室內","文化","親子"],"自然、歷史與藝術一次看，靠近新都心商場，是穩定的雨天方案。",150,"10:00",img.culture,aiko),
    add("shikinaen","識名園","spot","那霸","庭園",["文化","安靜","散步","歷史"],"琉球王家別邸庭園，遊客較少，適合想避開熱門人潮的人。",75,"10:00",img.park,official),
    add("chatan","美國村・Depot Island","spot","中部","海濱街區",["海景","購物","夕陽","夜間"],"餐廳、商店與海邊步道集中，建議從下午排到亮燈後。",180,"15:30",img.city,youtube,"北谷晚餐一起排，避免來回那霸。"),
    add("okinawa-zoo","沖繩兒童王國・Wonder Museum","spot","中部","動物園・兒童館",["親子","動物","雨天備案","放電"],"動物園加互動科學館，很適合學齡前與小學生，能玩半天。",240,"10:00",img.park,mimi,"當天只排這個主景點，午後留休息。"),
    add("southeast-botanical","東南植物樂園","spot","中部","植物園",["親子","自然","夜間","季節"],"熱帶植物、動物互動與季節燈飾，午後到晚上最有彈性。",180,"15:00",img.forest,mimi),
    add("katsuren","勝連城跡","spot","中部","世界遺產",["歷史","海景","健行","短停"],"城跡制高點能看海中道路，適合喜歡遺跡與景觀的人。",90,"10:00",img.culture,official),
    add("kaichu-road","海中道路・濱比嘉島","spot","中部","海景自駕",["自駕","海景","離島","慢遊"],"一路開往平安座島與濱比嘉島，沿途可停海灘和市場。",210,"10:00",img.sea,official,"和勝連城排成東海岸一日，別再跨到北谷。"),
    add("bios","Bios之丘","spot","中部","自然體驗",["親子","自然","遊船","放電"],"亞熱帶森林、湖上遊船與動物互動，適合親子慢玩。",180,"09:30",img.forest,official),
    add("parco","SAN-A 浦添西海岸 PARCO CITY","spot","中部","購物商場",["購物","雨天","海景","親子"],"海景商場、餐廳與品牌完整，雨天或採買日很好用。",150,"15:00",img.shop,aiko),
    add("aeon-rycom","AEON MALL 沖繩來客夢","spot","中部","購物商場",["購物","雨天","親子","美食"],"規模大、餐飲多，可作兒童王國或中部路線的備案。",150,"16:00",img.shop,mimi),
    add("cape-zanpa","殘波岬","spot","恩納・讀谷","海岬",["海景","夕陽","短停","免門票"],"白色燈塔與斷崖景觀，適合讀谷路線的傍晚短停。",60,"16:30",img.sea,official),
    add("yachimun","壺屋／讀谷陶器村","spot","恩納・讀谷","工藝文化",["文化","購物","手作","安靜"],"想看沖繩陶器與選器皿，可依住宿位置選壺屋或讀谷。",100,"10:30",img.culture,official),
    add("cape-maeda","真榮田岬・青之洞窟","spot","恩納・讀谷","海上活動",["浮潛","海景","預約","體力"],"人氣浮潛與潛水點，需依海況、年齡與體力選合格業者。",180,"09:00",img.sea,official,"不要和北部大型景點排同一天。"),
    add("manzamo","萬座毛","spot","恩納・讀谷","海岬",["經典","海景","短停","長輩"],"步道完整、停留時間好控制，適合沿西海岸順路停。",50,"15:00",img.sea,official),
    add("churaumi","沖繩美麗海水族館・海洋博公園","spot","北部","水族館",["經典","親子","雨天","一日"],"黑潮之海與戶外海洋博公園都值得留時間，是北部主景點。",240,"09:00",img.aquarium,mimi,"從那霸當日往返較累，盡量配北部住宿。"),
    add("bise","備瀨福木林道","spot","北部","聚落散步",["自然","單車","安靜","免門票"],"水族館旁的防風林聚落，可散步或騎單車，節奏舒服。",90,"15:30",img.forest,official),
    add("kouri","古宇利島・古宇利大橋","spot","北部","海景自駕",["海景","自駕","拍照","經典"],"跨海大橋與漸層藍海景是北部代表，可搭配咖啡或海灘。",150,"10:00",img.sea,mimi),
    add("nakijin","今歸仁城跡","spot","北部","世界遺產",["歷史","自然","健行","季節"],"石牆遺跡與山海景觀出色，櫻花季更熱門。",100,"09:30",img.culture,official),
    add("junglia","JUNGLIA OKINAWA","spot","北部","主題樂園",["新景點","親子","預約","一日"],"2025 開幕的北部大型樂園，想玩完整需獨立安排一天。",480,"09:00",img.forest,mimi,"票券、身高限制、接駁與營運資訊務必看官方。"),
    add("pineapple-park","名護鳳梨園","spot","北部","主題園區",["親子","雨天","小火車","購物"],"搭乘園區車看熱帶植物，伴手禮多，適合幼兒與雨天。",100,"14:00",img.forest,mimi),
    add("yanbaru","山原國立公園・大石林山","spot","北部","自然健行",["自然","健行","秘境","體力"],"沖繩本島北端的森林與石灰岩地形，適合喜歡自然深度旅行。",210,"09:00",img.forest,official,"車程長，建議北部住宿且不要與水族館同日。"),
    add("pork-egg","ポーたま 牧志市場店","food","那霸","飯糰・早餐",["早餐","外帶","親子","排隊"],"沖繩代表性的豬肉蛋飯糰，適合早餐或帶著走。",45,"09:00",img.sweet,foodBlog),
    add("shuri-soba","首里そば","food","那霸","沖繩麵",["在地","午餐","排隊","經典"],"手打麵條與清爽湯頭很有代表性，可接首里城路線。",60,"11:30",img.soba,foodBlog,"常提早售完，需確認營業日。"),
    add("jack-steak","Jack's Steak House","food","那霸","牛排",["經典","晚餐","排隊","美式"],"老字號美式牛排店，尖峰時間排隊長，適合保留備案。",90,"17:30",img.meat,foodBlog),
    add("ryukyu-no-ushi","琉球の牛 那覇國際通店","food","那霸","和牛燒肉",["燒肉","晚餐","預約","聚餐"],"住國際通時移動最輕鬆，多人家庭建議事先訂位。",120,"18:00",img.meat,aiko),
    add("motobu-yakiniku","燒肉もとぶ牧場 國際通店","food","那霸","品牌牛燒肉",["燒肉","晚餐","預約","聚餐"],"可品嚐沖繩品牌牛，國際通逛街後用餐方便。",120,"18:00",img.meat,foodBlog),
    add("daitoryo","大東ソバ","food","那霸","沖繩麵",["午餐","在地","麵食","國際通"],"麵條有嚼勁，地點靠近國際通，適合市區日快速午餐。",60,"12:00",img.soba,foodBlog),
    add("setsuko","節子鮮魚店","food","那霸","鮮魚料理",["海鮮","下午","在地","過敏注意"],"靠近美榮橋與那霸飯店區，可當下午短停或早晚餐。",60,"15:30",img.seafood,aiko,"蝦蟹過敏請先確認交叉接觸。"),
    add("jimmy-airport","Jimmy's 空港店","food","那霸","伴手禮",["伴手禮","機場","甜點","回程"],"蘋果派、大蒜麵包與香蕉蛋糕可在回程機場補買。",35,"13:30",img.sweet,aiko),
    add("itoman-fisher","糸滿漁民食堂","food","南部","海鮮定食",["海鮮","午餐","在地","親子"],"南部行程的熱門海鮮定食，適合接沖繩世界或糸滿市場。",75,"12:00",img.seafood,foodBlog,"先確認營業日；海鮮過敏請詢問共鍋。"),
    add("nakamoto-tempura","中本鮮魚天婦羅","food","南部","沖繩天婦羅",["小吃","外帶","在地","奧武島"],"奧武島人氣現炸天婦羅，買幾個分食最剛好。",35,"15:00",img.seafood,foodBlog),
    add("hamabe-chaya","浜邊茶屋","food","南部","海景咖啡",["海景","咖啡","慢遊","下午"],"靠海座位氣氛悠閒，適合南城路線放慢速度。",75,"14:30",img.cafe,aiko),
    add("curcuma","Cafe Curcuma","food","南部","海景泰式",["海景","午餐","咖哩","預約"],"南城高台海景餐廳，適合知念岬或齋場御嶽後午餐。",90,"12:00",img.cafe,aiko),
    add("posillipo","POSILLIPO cucina meridionale","food","南部","海景義式",["海景","晚餐","瀨長島","預約"],"瀨長島景觀餐廳，抵達日晚餐不用再移動。",110,"18:00",img.cafe,aiko),
    add("happy-pancake","幸福鬆餅 瀨長島店","food","南部","甜點",["海景","甜點","預約","下午"],"海景舒芙蕾適合下午休息，但別塞在趕時間的日子。",80,"15:00",img.sweet,aiko),
    add("kame-andagi","KAME ANDAGI","food","南部","沖繩甜甜圈",["甜點","外帶","親子","瀨長島"],"瀨長島散步時分食，時間比坐餐廳更彈性。",30,"16:00",img.sweet,aiko),
    add("king-tacos","King Tacos","food","中部","塔可飯",["在地","午餐","份量大","外帶"],"沖繩代表性塔可飯，份量大，家庭可分食。",60,"12:00",img.burger,foodBlog),
    add("payao","泡瀨漁港 パヤオ直売店","food","中部","海鮮市場",["海鮮","午餐","市場","在地"],"市場海鮮、龍蝦與生魚片選擇多，可配沖繩市行程。",75,"11:30",img.seafood,foodBlog),
    add("hamaya","浜屋沖繩麵","food","中部","沖繩麵",["午餐","在地","北谷","排隊"],"北谷人氣沖繩麵，走美國村或宮城海岸路線時順。",60,"11:30",img.soba,foodBlog),
    add("transit-cafe","Transit Cafe","food","中部","海景咖啡",["海景","咖啡","北谷","夕陽"],"宮城海岸旁的景觀咖啡，適合北谷午後慢慢坐。",80,"15:00",img.cafe,aiko),
    add("zhyvago","ZHYVAGO Coffee Roastery","food","中部","咖啡",["咖啡","海景","浦添","下午"],"港川與 PARCO CITY 路線都可找到順路分店。",60,"15:00",img.cafe,aiko),
    add("blue-seal","Blue Seal 冰淇淋","food","中部","冰品",["甜點","親子","沖繩味","短停"],"沖繩代表性冰品，分店多，適合當行程空檔而非特地繞路。",25,"15:30",img.sweet,aiko),
    add("aw","A&W 屋宜原店","food","中部","漢堡",["漢堡","親子","快速","美式"],"兒童王國附近的快速午餐備案，時間好控制。",55,"12:30",img.burger,mimi),
    add("paanilaani","Paanilani","food","恩納・讀谷","鬆餅早餐",["早餐","甜點","海岸","排隊"],"恩納村人氣美式鬆餅，適合西海岸住宿的早晨。",75,"09:00",img.sweet,foodBlog),
    add("sea-side-drivein","SEA SIDE DRIVE-IN","food","恩納・讀谷","美式餐廳",["美式","外帶","海景","宵夜"],"老字號美式餐廳，可外帶到海邊吃，時間彈性高。",65,"18:00",img.burger,foodBlog),
    add("cape-zanpa-cafe","星野 BANTA CAFE","food","恩納・讀谷","海景咖啡",["海景","咖啡","下午","預約"],"讀谷海岸大型景觀咖啡，空間寬但熱門時段仍可能等候。",90,"15:00",img.cafe,aiko),
    add("kishimoto","岸本食堂","food","北部","沖繩麵",["在地","午餐","老店","排隊"],"本部町老字號沖繩麵，可搭配水族館或備瀨。",60,"11:30",img.soba,foodBlog),
    add("kinokawa","紀乃川食堂","food","北部","沖繩定食",["在地","午餐","花生豆腐","家庭"],"花生豆腐與阿古豬定食具地方特色，水族館周邊可安排。",75,"12:00",img.soba,official),
    add("captain-kangaroo","Captain Kangaroo","food","北部","漢堡",["漢堡","午餐","份量大","排隊"],"名護人氣大份量漢堡，北部自駕時可作午餐。",75,"11:30",img.burger,foodBlog),
    add("kouri-shrimp","KOURI SHRIMP","food","北部","蝦飯",["海景","午餐","古宇利","外帶"],"古宇利島人氣蒜香蝦飯，適合海景路線，但熱門時會排隊。",65,"12:00",img.seafood,mimi,"蝦蟹過敏者不適合。"),
    add("bumbuntei","百年古家 大家","food","北部","阿古豬料理",["沖繩料理","午餐","古民家","預約"],"古民家與庭園氣氛完整，適合想吃正式沖繩料理的家庭。",100,"12:00",img.soba,aiko),
    add("old-ryoshi","漁師食堂","food","南部","海鮮定食",["舊版收藏","海鮮","午餐","過敏注意"],"原始清單保留店家；南部海鮮午餐選擇，安排前請再次確認店名、營業日與位置。",75,"12:00",img.seafood,foodBlog),
    add("old-itoman-fish-center","糸滿魚市場・鮮魚中心","food","南部","市場小吃",["舊版收藏","海鮮","市場","親子"],"生魚片、握壽司與熟食可各自挑選，也是多人家庭容易分流的午餐點。",75,"11:30",img.seafood,foodBlog),
    add("oshiro-tempura","大城天婦羅店","food","南部","奧武島小吃",["舊版收藏","小吃","外帶","在地"],"原始清單人氣現炸天婦羅店，適合奧武島散步時分食。",35,"15:00",img.seafood,foodBlog),
    add("gallirallus","Gallirallus 瀨長島","food","南部","九龍球・漸層果汁",["舊版收藏","飲料","瀨長島","親子"],"瀨長島散步時順買九龍球或漸層果汁，不需要另外繞路。",30,"16:30",img.sweet,aiko),
    add("sams-anchor","SAM'S Anchor Inn iias豐崎","food","南部","鐵板牛排",["舊版收藏","牛排","表演","親子"],"看廚師鐵板表演，逛 iias 時直接用餐，適合家庭聚餐。",100,"18:00",img.meat,aiko),
    add("aw-iias","A&W iias沖繩豐崎","food","南部","漢堡",["舊版收藏","漢堡","快速","親子"],"水族館或 iias 逛街時的快速用餐備案，時間容易控制。",55,"12:30",img.burger,aiko),
    add("rakusui","山之茶屋 樂水","food","南部","沖繩定食",["舊版收藏","自然","午餐","慢遊"],"自然系慢食餐廳，適合南城市景點之間放慢速度。",90,"12:00",img.soba,aiko),
    add("kunnato","くんなとぅ 海葡萄蕎麥麵","food","南部","海葡萄沖繩麵",["舊版收藏","沖繩麵","在地","午餐"],"南城市特色海藻料理，可和知念岬或齋場御嶽搭配。",70,"12:00",img.soba,foodBlog),
    add("old-pork-egg","豬肉蛋飯糰 牧志市場店","food","那霸","飯糰",["舊版收藏","早餐","外帶","親子"],"保留舊版中文名稱；早餐或外帶方便，孩子接受度高。",45,"09:00",img.sweet,foodBlog),
    add("danbo","暖暮拉麵","food","那霸","拉麵",["舊版收藏","拉麵","晚餐","國際通"],"國際通周邊晚餐備案，步行容易但熱門時可能排隊。",65,"18:00",img.soba,foodBlog),
    add("tondo-oroku","通堂拉麵 小祿本店","food","那霸","拉麵",["舊版收藏","拉麵","機場周邊","午餐"],"靠近機場區域，抵達或回程可依航班順路安排。",65,"12:00",img.soba,foodBlog),
    add("motobu-farm-naha","燒肉本部牧場 那霸店","food","那霸","燒肉",["舊版收藏","燒肉","晚餐","聚餐"],"家庭聚餐選擇，可品嚐沖繩品牌牛，建議事先訂位。",120,"18:00",img.meat,foodBlog),
    add("ushi-kokusai-old","琉球の牛 那覇國際通り店","food","那霸","沖繩和牛燒肉",["舊版收藏","燒肉","預約","聚餐"],"保留舊版店名寫法，住國際通時晚餐最省移動。",120,"18:00",img.meat,aiko),
    add("briand","ぶりあん（Briand）","food","那霸","黑毛和牛炭火燒肉",["舊版收藏","燒肉","個室","預約"],"牧志、美榮橋周邊的個室燒肉備案，適合想安靜聚餐的家庭。",120,"18:00",img.meat,aiko),
    add("ushi-kumoji","琉球の牛 那覇久茂地店","food","那霸","沖繩和牛燒肉",["舊版收藏","燒肉","久茂地","預約"],"靠近縣廳前與久茂地，適合國際通逛街後聚餐。",120,"18:00",img.meat,aiko),
    add("motobu-kokusai-old","燒肉もとぶ牧場 國際通り店","food","那霸","もとぶ牛燒肉",["舊版收藏","燒肉","國際通","聚餐"],"保留舊版店名寫法，適合多人共享套餐。",120,"18:00",img.meat,foodBlog),
    add("rikio-chatan","燒肉 RIKIO 北谷店","food","中部","燒肉",["舊版收藏","燒肉","北谷","晚餐"],"安排美國村或北谷行程時可作晚餐，不去北谷就不必繞路。",110,"18:00",img.meat,aiko),
    add("ushi-chatan","琉球の牛 北谷店","food","中部","沖繩和牛燒肉",["舊版收藏","燒肉","北谷","預約"],"中部海岸日的和牛晚餐選擇；若住那霸，優先選那霸分店。",120,"18:00",img.meat,aiko),
    add("naha-main-place","SAN-A 那霸 Main Place","spot","那霸","購物商場",["舊版收藏","購物","雨天","親子"],"新都心大型商場，靠近博物館，適合雨天採買與用餐。",120,"15:00",img.shop,aiko),
    add("palette-kumoji","Ryubo Department Store Palette久茂地","spot","那霸","百貨商場",["舊版收藏","購物","雨天","單軌"],"縣廳前站旁百貨，適合市區不開車日與回飯店前採買。",90,"15:30",img.shop,aiko),
    add("okinogu","沖宮","spot","那霸","神社",["舊版收藏","神社","文化","短停"],"位於奧武山公園一帶，可與機場、小祿或那霸南側路線合併。",50,"10:00",img.culture,official),
    add("gokoku-shrine","沖繩縣護國神社","spot","那霸","神社",["舊版收藏","神社","安靜","短停"],"奧武山公園旁的安靜參拜點，不需單獨跨區安排。",45,"10:30",img.culture,official),
    add("futenma-shrine","普天滿宮","spot","中部","神社・洞穴",["舊版收藏","神社","文化","雨天備案"],"中部代表神社之一，行程安排前可確認洞穴參拜開放方式。",60,"10:00",img.culture,official),
    add("shikina-shrine","識名宮","spot","那霸","神社",["舊版收藏","神社","文化","短停"],"那霸較安靜的神社收藏，適合與識名園或南部進出那霸時順遊。",45,"10:30",img.culture,official),
    add("little-universe","Little Universe OKINAWA","spot","南部","微縮主題館",["舊版收藏","親子","雨天","室內"],"位於豐崎的室內微縮主題館，可與 DMM 水族館、iias 做雨天組合。",120,"14:00",img.city,aiko),
    add("urasoe-park","浦添大公園","spot","中部","親子公園",["舊版收藏","親子","放電","免門票"],"大型溜滑梯與戶外空間，適合孩子放電，炎熱時避開正午。",90,"09:30",img.park,mimi),
    add("manko-wetland","漫湖水鳥・濕地中心","spot","那霸","自然教育",["舊版收藏","親子","自然","室內"],"免費的濕地生態教育點，適合機場周邊或雨勢不大時短停。",75,"10:00",img.forest,official),
    add("miibaru","新原海灘","spot","南部","海灘",["舊版收藏","海景","親子","玻璃船"],"南城市天然海灘，可依海況安排玻璃船或單純散步。",100,"14:00",img.sea,official),
    add("minatogawa","港川外人住宅","spot","中部","特色街區",["舊版收藏","咖啡","散步","拍照"],"老外人住宅改造的小店與咖啡街區，適合浦添半日慢遊。",90,"14:30",img.city,aiko),
    add("busena-marine","部瀨名海中公園","spot","北部","海中展望塔",["舊版收藏","親子","海景","玻璃船"],"海中展望塔與玻璃船適合不下水看海洋生物的家庭。",120,"10:00",img.aquarium,official),
    add("nago-castle-park","名護城公園","spot","北部","自然公園",["舊版收藏","自然","展望","免門票"],"名護市區的山景公園，櫻花季熱門，平時適合短停看景。",75,"15:00",img.park,official),
    add("sesoko","瀨底島","spot","北部","跨橋離島",["舊版收藏","海景","海灘","自駕"],"從本部跨橋即達，可與水族館或本部午餐合併。",120,"14:00",img.sea,official),
    add("minna-island","水納島","spot","北部","離島海灘",["舊版收藏","海景","船班","一日"],"需搭船前往的透明海水離島，適合獨立半日到一日，先確認船班。",300,"09:00",img.sea,official),
    add("yagaji","屋我地島","spot","北部","海景自駕",["舊版收藏","海景","自駕","慢遊"],"古宇利島前的安靜島嶼，可當北部自駕的順路景色而非獨立大點。",90,"14:00",img.sea,official),
    add("chimufugas-burger","氾濫漢堡 CHIMUFUGASU","food","南部","巨無霸漢堡",["瀨長島","特色美食","漢堡","份量大"],"瀨長島人氣大份量沖繩漢堡，視覺與份量都很有記憶點，適合多人分食。",65,"12:00",img.burger,umikaji,"排瀨長島午餐或傍晚早吃；份量大，後面甜點別排太緊。"),
    add("poke-boo","Poke Boo 瀨長島","food","南部","夏威夷生魚拌飯",["瀨長島","海鮮","輕食","海景"],"用海鮮與配料自由搭配的 Poke Bowl，想吃清爽一點時比漢堡更合適。",55,"12:30",img.seafood,umikaji,"適合午餐；不吃生食或有海鮮過敏時先確認配料。"),
    add("yukuru-gelato","yukuRu Gelato 瀨長島","food","南部","島素材義式冰淇淋",["瀨長島","甜點","親子","短停"],"用沖繩風味做成的義式冰淇淋，散步途中容易停、孩子也好選。",25,"15:30",img.sweet,umikaji,"當作瀨長島散步的其中一站即可，不必另外留一小時。"),
    add("and-shake","&shake okinawa","food","南部","奶昔・飲品",["瀨長島","甜點","飲料","拍照"],"色彩繽紛的奶昔與飲品很有度假感，適合想找特別拍照小食的人。",30,"16:00",img.sweet,umikaji,"和冰淇淋、鬆餅擇一即可，避免甜點連吃。"),
    add("motobu-aged-noodle","沖縄そば処 もとぶ熟成麺","food","南部","熟成沖繩麵",["瀨長島","沖繩麵","午餐","親子"],"想在瀨長島吃正餐時的在地麵食選擇，熟成麵條比一般觀光小食更有飽足感。",60,"12:00",img.soba,umikaji,"可和氾濫漢堡二選一，家庭成員也能分流選餐。"),
    add("motomu-curry-bread","もとむのカレーパン 瀨長島","food","南部","和牛咖哩麵包",["瀨長島","特色美食","外帶","短停"],"外酥內濃的咖哩麵包適合邊走邊吃，是不想坐下吃完整一餐的特色選項。",25,"15:00",img.sweet,umikaji,"當點心或分食即可；若已排正餐，不用再加一大份。"),
    add("by-the-shrimp","by・The・Shrimp 瀨長島","food","南部","蒜香蝦飯",["瀨長島","海鮮","特色美食","海景"],"南國感十足的蒜香蝦料理，適合想在海景旁吃較有沖繩度假感的午餐。",65,"12:00",img.seafood,umikaji,"蝦蟹過敏者略過；和 Poke Bowl 擇一即可。"),
    add("kijimunaa-senaga","タコライスcafe きじむなぁ 瀨長島","food","南部","蛋包塔可飯",["瀨長島","塔可飯","親子","特色美食"],"可選蛋包版本的沖繩塔可飯，口味與份量對家庭較好分享。",60,"12:00",img.meat,umikaji,"適合抵達日早晚餐或瀨長島午餐，尖峰時段預留等位。"),
    add("whitedog-burger","WHITEdog BURGER 瀨長島","food","南部","熱狗・漢堡",["瀨長島","漢堡","輕食","親子"],"想吃美式街頭小食、又不想挑戰巨無霸份量時的另一個瀨長島選擇。",45,"13:00",img.burger,umikaji,"與氾濫漢堡屬同類型，同一天選一間最剛好。"),
    add("sunroom-sweets","SunRoom Sweets SENAGAJIMA","food","南部","水果甜點",["瀨長島","甜點","水果","親子"],"水果系甜點與飲品適合炎熱午後，安排成散步中的短休息即可。",35,"15:30",img.sweet,umikaji,"當日若已排幸福鬆餅，建議改選飲品或直接略過。"),
    add("teamlab-future-naha","teamLab Future Park 沖繩・那霸","spot","那霸","互動數位藝術",["親子","雨天","室內","互動"],"孩子畫出的圖像會進入數位空間，適合學齡前到小學生一起玩的室內親子點。",120,"10:00",img.city,familyIndoor,"雨天優先；先確認當期場地、票券與入場時段。"),
    add("kids-palette","The Kids Palette 久茂地","spot","那霸","室內遊戲場",["親子","雨天","室內","幼兒"],"那霸市中心的室內遊戲選項，不開車日或突然下雨時容易插入。",100,"10:00",img.park,familyJapan,"適合幼兒放電；先確認年齡、襪子與陪同規定。"),
    add("naminoue-kidsland","波の上わくわくキッズランド","spot","那霸","室內親子樂園",["親子","雨天","室內","放電"],"球池與攀爬遊具類型的室內放電點，可和波上宮、那霸市區一起排。",120,"14:00",img.park,familyJapan,"雨天備案，不建議再搭另一個大型室內樂園。"),
    add("asobi-park-parco","あそびパークPLUS PARCO CITY","spot","中部","室內遊戲場",["親子","雨天","室內","購物"],"位於 PARCO CITY，家長能把孩子放電、用餐與採買集中在同一站。",100,"14:00",img.park,familyJapan,"和 PARCO CITY 合併，不另外計算跨區時間。"),
    add("chikyu-no-niwa-rycom","ちきゅうのにわ 沖繩來客夢","spot","中部","自然主題室內樂園",["親子","雨天","室內","幼兒"],"結合自然主題與遊戲設施，適合把 AEON MALL 來客夢變成完整雨天親子半日。",120,"14:00",img.park,familyJapan,"和兒童王國二選一；孩子仍有體力再加商場用餐。"),
    add("round1-ginowan","ROUND1 Stadium 宜野灣店","spot","中部","室內運動娛樂",["親子","雨天","室內","學童"],"保齡球、運動與遊戲適合較大的孩子，遇到豪雨也能消耗體力。",150,"14:00",img.city,familyJapan,"較適合學童與青少年；先確認各設施年齡限制。"),
    add("yanbaru-toy-museum","やんばる森のおもちゃ美術館","spot","北部","木育玩具館",["親子","雨天","室內","幼兒"],"以木製玩具和山原自然為主題，節奏安靜，適合幼兒與需要休息型活動的家庭。",100,"10:30",img.forest,familyJapan,"位於北部，建議搭北部住宿或山原路線，不從那霸單獨往返。"),
    add("neo-park","名護自然動植物公園 Neo Park Okinawa","spot","北部","動植物園・小火車",["親子","動物","小火車","戶外"],"可近距離看動物並搭園區小火車，適合不想走超大型樂園的家庭。",150,"10:00",img.park,mimi,"避開正午曝曬；雨大時改選室內備案。"),
    add("dino-park-nago","DINO 恐龍 PARK・御菓子御殿名護店","spot","北部","恐龍森林步道",["親子","恐龍","森林","幼兒"],"森林步道裡有大量恐龍模型，停留時間好控制，也能順便補伴手禮。",90,"14:00",img.forest,mimi,"適合喜歡恐龍的幼兒；下雨時步道可能濕滑。"),
    add("tropical-dream-center","熱帶夢幻中心","spot","北部","熱帶植物園",["親子","雨天備案","植物","海洋博公園"],"海洋博公園內較安靜的熱帶植物展館，可在水族館人潮多或天氣變化時替換。",100,"14:30",img.forest,official,"和美麗海水族館同園區安排，不另開一個北部日。")
  ];
  // 舊版固定收藏重新以官方店名、實際分店與完整地址校正；重複卡片併回既有正確資料。
  const duplicateLegacyIds=new Set(["old-ryoshi","old-itoman-fish-center","old-pork-egg","ushi-kokusai-old","motobu-kokusai-old"]);
  const verifiedLegacy={
    "oshiro-tempura":{name:"大城てんぷら店",source:"https://www.kankou-nanjo.okinawa/eat/61/",mapQuery:"大城てんぷら店 沖縄県南城市玉城奥武193",desc:"奧武島現炸天婦羅老店，魚、魷魚與蔬菜可分食；熱門時段可能排隊。"},
    gallirallus:{source:"https://www.umikajiterrace.com/profile/gallirallus/",mapQuery:"Gallirallus 瀬長島ウミカジテラス 沖縄県豊見城市瀬長174-6",desc:"瀨長島 Umikaji Terrace 的九龍球與漸層飲品店，適合散步途中短停。"},
    "sams-anchor":{name:"SAM'S Anchor Inn iias沖繩豐崎店",source:"https://www.sams-okinawa.jp/topics/detail.jsp?id=428&target=egtopics",mapQuery:"SAM'S Anchor Inn iias沖縄豊崎店 沖縄県豊見城市豊崎3-35 2F"},
    "aw-iias":{name:"A&W iias沖繩豐崎店",source:"https://www.awok.co.jp/shopsearch/iiasokinawa/",mapQuery:"A&W イーアス沖縄豊崎店 沖縄県豊見城市豊崎3-35"},
    rakusui:{source:"https://sachibaru.jp/yamacha/",mapQuery:"山の茶屋 楽水 沖縄県南城市玉城玉城19-1",desc:"坐在綠意與海風之間吃沖繩定食的慢食餐廳；山坡入口與營業日要先確認。"},
    kunnato:{name:"もずくそばの店 くんなとぅ",source:"https://www.mozuku-soba.com/",mapQuery:"もずくそばの店 くんなとぅ 沖縄県南城市玉城志堅原460-2",category:"海藻沖繩麵"},
    danbo:{name:"暖暮 那霸牧志店",source:"https://ramendanbo.okinawa/locations-2/",mapQuery:"ラーメン暖暮 那覇牧志店 沖縄県那覇市牧志2-16-10",desc:"牧志站附近的豚骨拉麵店；是國際通晚餐備案，熱門時段可能排隊。"},
    "tondo-oroku":{name:"琉球新麵 通堂 小祿本店",source:"https://www.ryoji-family.co.jp/store.php",mapQuery:"琉球新麺 通堂 小禄本店 沖縄県那覇市金城5-4-6"},
    "motobu-farm-naha":{name:"焼肉 もとぶ牧場 那霸店",source:"https://motobu-farm.com/pages/store-naha",mapQuery:"焼肉 もとぶ牧場 那覇店 沖縄県那覇市久茂地2-1-3 久茂地MKビル3F",category:"もとぶ牛燒肉"},
    briand:{name:"ぶりあん（那霸牧志）",source:"https://briand.owst.jp/",mapQuery:"ぶりあん 沖縄県那覇市牧志1丁目4-43 新川ビル1F",category:"黑毛和牛菲力・夏多布里昂",desc:"全席個室的黑毛和牛菲力專門店，靠近美榮橋與國際通；屬高價位套餐，訂位前先確認兒童與套餐規定。",tip:"想吃精緻和牛再選這間；價格較高，建議先看官方套餐與訂位規則。"},
    "ushi-kumoji":{name:"琉球の牛 那霸久茂地店",source:"https://www.u-shi.net/kumoji.html",mapQuery:"琉球の牛 那覇久茂地店 沖縄県那覇市久茂地3-16-1",category:"沖繩縣產和牛燒肉"},
    "rikio-chatan":{name:"焼肉 RIKIO 北谷店",source:"https://yakiniku-rikio.com/access/",mapQuery:"焼肉 RIKIO 沖縄県中頭郡北谷町美浜9-19 ディストーションファッションビル2F"},
    "ushi-chatan":{name:"琉球の牛 北谷店",source:"https://www.u-shi.net/chatan.html",mapQuery:"琉球の牛 北谷店 沖縄県中頭郡北谷町美浜51-1",category:"沖繩縣產和牛燒肉"},
    "naha-main-place":{name:"SAN-A 那霸 Main Place",source:"https://blog-nahamainplace.san-a.co.jp/shoplist/",mapQuery:"サンエー那覇メインプレイス 沖縄県那覇市おもろまち4-4-9"},
    "palette-kumoji":{name:"Palette久茂地・百貨公司 Ryubo",source:"https://ryubo.jp/",mapQuery:"デパートリウボウ パレットくもじ 沖縄県那覇市久茂地1-1-1",category:"百貨商場"},
    okinogu:{source:"https://okinogu.or.jp/",mapQuery:"沖宮 沖縄県那覇市奥武山町44",desc:"位於奧武山公園內的琉球八社之一，可與護國神社或小祿路線順遊。"},
    "gokoku-shrine":{name:"沖繩縣護國神社",source:"https://okinawa-gokoku.jp/access/",mapQuery:"沖縄県護国神社 沖縄県那覇市奥武山町44"},
    "futenma-shrine":{name:"普天滿宮",source:"https://futenmagu.or.jp/",mapQuery:"普天満宮 沖縄県宜野湾市普天間1-27-10",desc:"中部代表神社，可申請參拜本殿後方洞穴；出發前先看官方開放方式。"},
    "shikina-shrine":{name:"識名宮",source:"https://www.google.com/maps/search/?api=1&query=%E8%AD%98%E5%90%8D%E5%AE%AE%20%E6%B2%96%E7%B9%A9",mapQuery:"識名宮 沖縄県那覇市繁多川4-1-43"},
    "little-universe":{name:"Little Universe OKINAWA",source:"https://www.little-universe.com/",mapQuery:"Little Universe OKINAWA 沖縄県豊見城市豊崎3-35 イーアス沖縄豊崎3F",desc:"位於 iias 豐崎 3 樓的全天候親子體驗館，可與 DMM 水族館合併成雨天半日。"},
    "urasoe-park":{name:"浦添大公園・ふれあい廣場",source:"https://www.urasoedaipark-osi.jp/",mapQuery:"浦添大公園 ふれあい広場 沖縄県浦添市仲間2-53",desc:"大型溜滑梯與戶外放電區，導航直接設ふれあい廣場；炎熱時避開正午。"},
    "manko-wetland":{name:"漫湖水鳥・濕地中心",area:"南部",source:"https://www.manko-mizudori.net/",mapQuery:"漫湖水鳥・湿地センター 沖縄県豊見城市豊見城982",desc:"位於豐見城市的免費濕地生態中心，不是在那霸市中心；適合機場南側短停。"},
    miibaru:{name:"新原海灘（Mibaru Beach）",source:"https://www.kankou-nanjo.okinawa/enjoy/20/",mapQuery:"新原ビーチ 沖縄県南城市玉城百名1346"},
    minatogawa:{name:"港川 Stateside Town（外人住宅街）",source:"https://www.bunka.go.jp/kindai/kenzoubutsu/research/okinawa/004/index.html",mapQuery:"港川ステイツサイドタウン 沖縄県浦添市港川2丁目18"},
    "busena-marine":{name:"部瀨名海中公園",source:"https://www.busena-marinepark.com/",mapQuery:"ブセナ海中公園 沖縄県名護市喜瀬1744-1"},
    "nago-castle-park":{name:"名護城公園",source:"https://www.nangusuku-osi.jp/",mapQuery:"名護城公園 沖縄県名護市名護5511"},
    sesoko:{name:"瀨底島・瀨底海灘",source:"https://www.motobu-ka.com/tourist_info/tourist_info-post-696/",mapQuery:"瀬底ビーチ 沖縄県国頭郡本部町瀬底5583-1",desc:"從本部跨橋即達；若要玩水請直接導航瀨底海灘，可與水族館或本部午餐合併。"},
    "minna-island":{name:"水納島（渡久地港搭船）",source:"https://www.town.motobu.okinawa.jp/doc/2023113000024/",mapQuery:"渡久地港 水納島航路旅客待合所 沖縄県国頭郡本部町谷茶29",desc:"需從渡久地港搭船，適合獨立半日到一日；先以水納海運官方時刻與海況為準。"},
    yagaji:{name:"屋我地島・屋我地海灘",source:"https://yagaji-beach.com/",mapQuery:"屋我地ビーチ 沖縄県名護市屋我143",desc:"古宇利島前的安靜島嶼與海灘，可作北部自駕順路短停，不必單獨排一天。"}
  };
  window.OKINAWA_LIBRARY=window.OKINAWA_LIBRARY.filter(place=>!duplicateLegacyIds.has(place.id));
  window.OKINAWA_LIBRARY.forEach(place=>{if(verifiedLegacy[place.id])Object.assign(place,verifiedLegacy[place.id])});
  window.OKINAWA_SOURCES=[
    {label:"沖繩官方觀光指南",url:"https://visitokinawajapan.com/zh-hant/destinations/okinawa-main-island/"},
    {label:"Mimi韓｜2025 親子行程",url:mimi},{label:"Mimi韓｜2025 沖繩美食",url:foodBlog},{label:"aiko｜沖繩自由行整理",url:aiko},
    {label:"瀨長島官方｜餐廳與商店",url:umikaji},{label:"2026 沖繩親子雨天景點",url:familyIndoor},{label:"沖繩親子室內景點整理",url:familyJapan},
    {label:"YouTube｜沖繩自駕五日攻略",url:youtube},{label:"YouTube｜四天三夜景點美食",url:"https://www.youtube.com/watch?v=U4Y8rOY1BEg"}
  ];
})();
